Traceback (most recent call last):
  File "C:/ZZZZZZZZZZ/python/base/02_4_快速上手_调试.py", line 28, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
